version: '3.8'
services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
  celery_worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis
  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

