# Generated by Django 5.0.4 on 2024-04-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('completed_users_groups', models.ManyToManyField(blank=True, related_name='completion_groups', to='groups.group')),
                ('policies', models.ManyToManyField(related_name='campaigns', to='policies.policy')),
                ('target_groups', models.ManyToManyField(related_name='targeted_campaigns', to='groups.group')),
            ],
        ),
    ]
