# Generated by Django 5.0.4 on 2024-05-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('groups', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='completed_users_groups',
            field=models.ManyToManyField(blank=True, related_name='completion_groups', to='groups.groupmetadata'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='policies',
            field=models.ManyToManyField(related_name='campaigns', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_groups',
            field=models.ManyToManyField(related_name='targeted_campaigns', to='groups.groupmetadata'),
        ),
    ]
