# Generated by Django 5.0.4 on 2024-05-22 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-id']},
        ),
    ]
