# Generated by Django 5.0.4 on 2024-05-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_completed_users_groups_and_more'),
        ('groups', '0003_alter_groupmetadata_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='completed_users_groups',
            field=models.ManyToManyField(blank=True, related_name='completion_groups', to='groups.groupmetadata'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_groups',
            field=models.ManyToManyField(related_name='targeted_campaigns', to='groups.groupmetadata'),
        ),
    ]
