# Generated by Django 5.0.4 on 2024-04-30 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('campaigns', '0002_alter_campaign_completed_users_groups_and_more'),
        ('groups', '0001_initial'),
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='auth.group')),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
