# Generated by Django 5.0.4 on 2024-04-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupmetadata_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmetadata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
