# Generated by Django 5.0.4 on 2024-05-13 17:30

import apps.policies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50)),
                ('min_read_time', models.PositiveIntegerField(help_text='Minimum time required to read the policy in minutes.')),
                ('allow_download', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('pa', 'Punjabi'), ('te', 'Telugu'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('ur', 'Urdu'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('or', 'Odia'), ('ml', 'Malayalam'), ('my', 'Burmese'), ('th', 'Thai'), ('vi', 'Vietnamese'), ('id', 'Indonesian'), ('tl', 'Filipino'), ('ms', 'Malay'), ('sw', 'Swahili'), ('am', 'Amharic'), ('yo', 'Yoruba'), ('ha', 'Hausa'), ('zu', 'Zulu'), ('xh', 'Xhosa'), ('st', 'Sesotho'), ('sn', 'Shona'), ('so', 'Somali'), ('sw', 'Swahili'), ('mg', 'Malagasy'), ('km', 'Khmer'), ('lo', 'Lao'), ('ne', 'Nepali'), ('si', 'Sinhala'), ('my', 'Burmese'), ('ka', 'Georgian')], max_length=2)),
                ('localized_title', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to=apps.policies.models.upload_to_language_document)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='policies.policy')),
            ],
        ),
    ]
