# Generated by Django 5.0.4 on 2024-05-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('unnoticed', 'Unnoticed'), ('acknowledgement', 'Acknowledgement')], default='draft', max_length=50),
        ),
    ]
