# Generated by Django 5.0.4 on 2024-05-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_language_options_alter_policy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('unnoticed', 'Unnoticed'), ('acknowledgement', 'Acknowledgement')], default='unnoticed', max_length=50),
        ),
    ]
